// authController Status Codes
const USER_NAME_IS_NOT_PROVIDED = 600;
const NAME_OF_USER_IS_NOT_PROVIDED = 601;
const USER_PRIMARY_EMAIL_IN_NOT_PROVIDED = 602;
const USER_PASSWORD_IS_NOT_PROVIDED = 603;
const USER_ALREADY_EXIST = 604;
const AUTHENTICATION_TOKEN_GENERATION_ERROR = 605;
const AUTHENTICATION_TOKEN_IS_GENERATED = 606;
const USER_NOT_EXIST = 607;
const USER_INVALID_CREDENTIAL = 608;
const USER_REGISTERED_SUCCESSFULLY = 609;
const USER_CREDENTIAL_VERIFIED = 610;
const USER_VERIFIED_WITH_AUTHENTICATION_TOKEN = 611;
const USER_UPDATED_SUCCESSFULLY = 613;

module.exports = {
    USER_NAME_IS_NOT_PROVIDED,
    NAME_OF_USER_IS_NOT_PROVIDED,
    USER_PRIMARY_EMAIL_IN_NOT_PROVIDED,
    USER_PASSWORD_IS_NOT_PROVIDED,
    USER_ALREADY_EXIST,
    AUTHENTICATION_TOKEN_GENERATION_ERROR,
    AUTHENTICATION_TOKEN_IS_GENERATED,
    USER_NOT_EXIST,
    USER_INVALID_CREDENTIAL,
    USER_REGISTERED_SUCCESSFULLY,
    USER_CREDENTIAL_VERIFIED,
    USER_VERIFIED_WITH_AUTHENTICATION_TOKEN,
    USER_UPDATED_SUCCESSFULLY,
}

// userController Status Codes
const FETCH_ALL_USERS_IS_SUCCESSFUL = 620;
const USER_FOUND_SUCCESSFULLY = 621;

module.exports = {
    FETCH_ALL_USERS_IS_SUCCESSFUL,
    USER_FOUND_SUCCESSFULLY,
}

// taskController Status Codes
const TASK_FETCHED_SUCCESSFULLY = 630;
const TASK_CREATOR_IS_NOT_PROVIDED = 631;
const TASK_TITLE_IS_NOT_PROVIDED = 632;
const TASK_BASICDETAILS_IS_NOT_PROVIDED = 633;
const TASK_TIMINGANDSCHEDULE_IS_NOT_PROVIDED = 634;
const TASK_CREATED_SUCCESSFULLY = 635;
const TASK_UPDATED_SUCCESSFULLY = 636;
const TASK_NOT_FOUND = 637;
const TASK_DELETED_SUCCESSFULLY = 638;

module.exports = {
    TASK_FETCHED_SUCCESSFULLY,
    TASK_CREATOR_IS_NOT_PROVIDED,
    TASK_TITLE_IS_NOT_PROVIDED,
    TASK_BASICDETAILS_IS_NOT_PROVIDED,
    TASK_TIMINGANDSCHEDULE_IS_NOT_PROVIDED,
    TASK_CREATED_SUCCESSFULLY,
    TASK_UPDATED_SUCCESSFULLY,
    TASK_NOT_FOUND,
    TASK_DELETED_SUCCESSFULLY,
}

// teamController Status Codes
const TEAM_NOT_FOUND = 640;
const TEAM_FOUND_SUCCESSFULLY = 641;
const TEAMNAME_IS_NOT_PROVIDED = 642;
const TEAM_BASICDETAILS_IS_NOT_PROVIDED = 643;
const TEAM_MEMBERS_IS_NOT_PROVIDED = 644;
const TEAM_LEADER_IS_NOT_PROVIDED = 645;
const TEAM_MEMBER_NOT_FOUND_IN_USER_DATABASE = 646;
const TEAM_CREATED_SUCCESSFULLY = 647;
const TEAM_UPDATED_SUCCESSFULLY = 648;
const TEAM_DELETED_SUCCESSFULLY = 649;

module.exports = {
    TEAM_NOT_FOUND,
    TEAM_FOUND_SUCCESSFULLY,
    TEAMNAME_IS_NOT_PROVIDED,
    TEAM_BASICDETAILS_IS_NOT_PROVIDED,
    TEAM_MEMBERS_IS_NOT_PROVIDED,
    TEAM_LEADER_IS_NOT_PROVIDED,
    TEAM_MEMBER_NOT_FOUND_IN_USER_DATABASE,
    TEAM_CREATED_SUCCESSFULLY,
    TEAM_UPDATED_SUCCESSFULLY,
    TEAM_DELETED_SUCCESSFULLY,
}

// supervisorController Status Codes
const SUPERVISOR_NOT_FOUND = 660;
const SUPERVISOR_FOUND_SUCCESSFULLY = 661;
const SUPERVISOR_NAME_IS_NOT_PROVIDED = 662;
const SUPERVISOR_PRIMARYEMAIL_IS_NOT_PROVIDED = 663;
const SUPERVISOR_ADDED_SUCCESSFULLY = 664;
const SUPERVISOR_UPDATED_SUCCESSFULLY = 665;
const SUPERVISOR_REMOVED_SUCCESSFULLT = 666;

module.exports = {
    SUPERVISOR_NOT_FOUND,
    SUPERVISOR_FOUND_SUCCESSFULLY,
    SUPERVISOR_NAME_IS_NOT_PROVIDED,
    SUPERVISOR_PRIMARYEMAIL_IS_NOT_PROVIDED,
    SUPERVISOR_ADDED_SUCCESSFULLY,
    SUPERVISOR_UPDATED_SUCCESSFULLY,
    SUPERVISOR_REMOVED_SUCCESSFULLT,
}

// authMiddleware Status Codes
const TOKEN_NOT_GENERATED = 700;
const TOKEN_EXPIRES = 701;

module.exports = {
    TOKEN_NOT_GENERATED,
    TOKEN_EXPIRES,
}

// mongoDB server error Status Codes
const MONGODB_SERVER_ERROR_FIND = 800;
const MONGODB_SERVER_ERROR_FINDBYID = 801;
const MONGODB_SERVER_ERROR_FINDBYIDANDDELETE = 802;
const MONGODB_SERVER_ERROR_FINDBYIDANDUPDATE = 803;
const MONGODB_SERVER_ERROR_FINDONE = 804;
const MONGODB_SERVER_ERROR_FINDONEANDDELETE = 805;
const MONGODB_SERVER_ERROR_FINDONEANDREPLACE = 806;
const MONGODB_SERVER_ERROR_FINDONEANDUPDATE = 807;
const MONGODB_SERVER_ERROR_SAVE = 808;

module.exports = {
    MONGODB_SERVER_ERROR_FIND,
    MONGODB_SERVER_ERROR_FINDBYID,
    MONGODB_SERVER_ERROR_FINDBYIDANDDELETE,
    MONGODB_SERVER_ERROR_FINDBYIDANDUPDATE,
    MONGODB_SERVER_ERROR_FINDONE,
    MONGODB_SERVER_ERROR_FINDONEANDDELETE,
    MONGODB_SERVER_ERROR_FINDONEANDREPLACE,
    MONGODB_SERVER_ERROR_FINDONEANDUPDATE,
    MONGODB_SERVER_ERROR_SAVE,
}

// Internal server error Status Codes
const INTERNAL_SERVER_ERROR_BCRYPT_COMPARE = 900;

module.exports = {
    INTERNAL_SERVER_ERROR_BCRYPT_COMPARE,
}